spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookbd?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    password: amizoneng1
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update

  mail:
    host: smtp.gmail.com
    port: 587
    username: ngouoleonel3@gmail.com
    password: wlax zthp fymp nfoi
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
